server:
  port: 9010
spring:
  profiles:
    active: dev


pageSize: 2
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
---
spring:
  profile: prod
  data:
    mongodb:
      host: localhost
      port: 27018
      database: hourglass
