server:
  port: 9010
spring:
  profiles:
    active: dev


pageSize: 2
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      output-tasks:
        destination: tasks
    defaultBinder: rabbit
    default.contentType: application/json
spring.rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

---
spring:
  profile: prod
  data:
    mongodb:
      host: hourglassdb-service
      port: 27017
      database: hourglass
  cloud.stream:
    bindings:
      output-tasks:
        destination: tasks

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest
